version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/core"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "area: backend"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "area: frontend"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "area: infra"
